routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('space', 'SpaceController');
Route::get('/browse/space', 'SpaceController@browse')->name('space.browse');

app/Space.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Space extends Model
{
    //
    protected $guarded = [];

    public function photos()
    {
        return $this->hasMany(SpacePhoto::class, 'space_id', 'id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function getSpaces($latitude, $longitude, $radius)
    {
        return $this->select('spaces.*')
            ->selectRaw(
                '( 6371 *
                    acos( cos( radians(?) ) *
                        cos( radians( latitude ) ) *
                        cos( radians(longitude ) - radians(?)) +
                        sin( radians(?) ) *
                        sin( radians( latitude ) )
                    )
                ) AS distance', [$latitude, $longitude, $latitude]
            )
            ->havingRaw("distance < ?", [$radius])
            ->orderBy('distance', 'asc');
    }
}

app/SpacePhoto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SpacePhoto extends Model
{
    //
    protected $guarded = [];

    public function space()
    {
        return $this->belongsTo(Space::class, 'space_id', 'id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function spaces()
    {
        return $this->hasMany(Space::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Api/SpaceController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Space;
use Illuminate\Http\Request;

class SpaceController extends Controller
{
    //
    public function getSpaces(Request $request)
    {
        $space = new Space();
        return $space->getSpaces($request->lat, $request->lng, $request->rad)->get();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SpaceController.php
<?php

namespace App\Http\Controllers;

use App\Space;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class SpaceController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $spaces = Space::orderBy('created_at', 'DESC')->paginate(10);
        return view('pages.space.index', compact('spaces'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('pages.space.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'title' => ['required', 'min:3'],
            'address' => ['required', 'min:5'],
            'description' => ['required', 'min:5'],
            'latitude' => ['required'],
            'longitude' => ['required'],
        ]);

        $request->user()->spaces()->create($request->all());
        return redirect()->route('space.index')->with('status', 'Space created');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show(Request $request, $id)
    {
        //
        $space = Space::findOrFail($id);
        return view('pages.space.show', compact('space'));
    }

    public function browse()
    {
        return view('pages.space.browse');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        //
        $space = Space::findOrFail($id);
        if ($space->user_id != request()->user()->id) {
            return redirect()->back();
        }
        return view('pages.space.edit', compact('space'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
        $space = Space::findOrFail($id);
        if ($space->user_id != request()->user()->id) {
            return redirect()->back();
        }
        $this->validate($request, [
            'title' => ['required', 'min:3'],
            'address' => ['required', 'min:5'],
            'description' => ['required', 'min:5'],
            'latitude' => ['required'],
            'longitude' => ['required'],
        ]);
        $space->update($request->all());
        return redirect()->route('space.index')->with('status', 'Space updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
        $space = Space::findOrFail($id);
        if ($space->user_id != request()->user()->id) {
            return redirect()->back();
        }
        $space->delete();
        return redirect()->route('space.index')->with('status', 'Space deleted!');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        You are logged in!
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-ui.js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css"/>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js" type="text/javascript" charset="utf-8"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @stack('style')
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="{{route('space.index')}}" class="nav-link">Space</a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>

<script src="{{ asset('js/app.js') }}" defer></script>
@stack('script')
<script>
    window.hereApiKey = "{{env('HERE_API_KEY')}}"
</script>
<script src="{{asset('js/here.js')}}"></script>

</body>
</html>

resources/views/pages/space/browse.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <x-space></x-space>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Browse CodeSpace</div>

                    <div class="card-body">
                        <div id="mapContainer" style="height: 500px"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        window.action = "browse"
    </script>
@endpush

resources/views/pages/space/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <x-navigation></x-navigation>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Submit My Space</div>
                    <div class="card-body">
                        {!! Form::open(['route'=> 'space.store', 'method' => 'post','files' => true]) !!}
                        <div class="form-group">
                            <label for="">Title</label>
                            {!! Form::text('title', null, ['class'=>$errors->has('title')
                                ? 'form-control is-invalid'
                                : 'form-control' ])
                            !!}
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Address</label>
                            {!! Form::textarea('address', null, [
                                'class'=>$errors->has('address') ? 'form-control is-invalid' : 'form-control',
                                'cols'=>"10",
                                'rows'=>"3"
                            ]) !!}
                            @error('address')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Description</label>
                            {!! Form::textarea('description', null, [
                                'class'=>$errors->has('description') ? 'form-control is-invalid' : 'form-control',
                                'cols'=>"10",
                                'rows'=>"3"
                            ]) !!}
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div id="here-maps">
                            <label for="">Pin Location</label>
                            <div id="mapContainer" style="height: 500px"></div>
                        </div>
                        <div class="form-group">
                            <label for="">Latitude</label>
                            {!! Form::text('latitude', null, [
                                'class'=>$errors->has('latitude')? 'form-control is-invalid': 'form-control',
                                'id'=>'lat'
                                ])
                            !!}
                            @error('latitude')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Longitude</label>
                            {!! Form::text('longitude', null, [
                                'class'=>$errors->has('longitude')? 'form-control is-invalid': 'form-control',
                                'id'=>'lng'
                                ])
                            !!}
                            @error('longitude')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        window.action = "submit"
    </script>
@endpush

resources/views/pages/space/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <x-navigation></x-navigation>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Submit My Space</div>
                    <div class="card-body">
                        {!! Form::model($space,['route'=> ['space.update', $space->id],
                            'method' => 'put','files' => true]) !!}
                        <div class="form-group">
                            <label for="">Title</label>
                            {!! Form::text('title', null, ['class'=>$errors->has('title')
                                ? 'form-control is-invalid'
                                : 'form-control' ])
                            !!}
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Address</label>
                            {!! Form::textarea('address', null, [
                                'class'=>$errors->has('address') ? 'form-control is-invalid' : 'form-control',
                                'cols'=>"10",
                                'rows'=>"3"
                            ]) !!}
                            @error('address')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Description</label>
                            {!! Form::textarea('description', null, [
                                'class'=>$errors->has('description') ? 'form-control is-invalid' : 'form-control',
                                'cols'=>"10",
                                'rows'=>"3"
                            ]) !!}
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div id="here-maps">
                            <label for="">Pin Location</label>
                            <div id="mapContainer" style="height: 500px"></div>
                        </div>
                        <div class="form-group">
                            <label for="">Latitude</label>
                            {!! Form::text('latitude', null, [
                                'class'=>$errors->has('latitude')? 'form-control is-invalid': 'form-control',
                                'id'=>'lat'
                                ])
                            !!}
                            @error('latitude')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Longitude</label>
                            {!! Form::text('longitude', null, [
                                'class'=>$errors->has('longitude')? 'form-control is-invalid': 'form-control',
                                'id'=>'lng'
                                ])
                            !!}
                            @error('longitude')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{$message}}</strong>
                                </span>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        window.action = "submit"
    </script>
@endpush

resources/views/pages/space/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <x-space></x-space>
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                @foreach($spaces as $space)
                    <div class="card">
                        <div class="card-header">Space</div>
                        <div class="card-body">
                            <h5 class="card-title">
                                {{$space->title}}
                                @if ($space->user_id == Auth::user()->id)
                                    <form action="{{route('space.destroy', $space->id)}}" method="post">
                                        @csrf   @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger float-right"
                                                onclick="return confirm('are you sure ?');">
                                            Delete
                                        </button>
                                        <a href="{{route('space.edit', $space->id)}}"
                                           class="btn btn-sm btn-info float-right text-white">Edit</a>
                                    </form>
                                @endif
                            </h5>
                            <h6 class="card-subtitle">{{$space->address}}</h6>
                            <p class="card-text">{{$space->description}}</p>
                            <a href="#"
                               onclick="openDirection({{$space->latitude}}, {{$space->longitude}}, {{$space->id}})"
                               class="card-link">
                                Direction
                            </a>
                        </div>
                    </div>
                    @endforeach
            </div>
        </div>
        <div class="row justify-content-center">
            {{$spaces->links()}}
        </div>
    </div>
@endsection

resources/views/pages/space/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <x-navigation></x-navigation>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-header">Space: {{$space -> title}}</div>
                    <div class="card-body">
                        <div id="mapContainer" style="height: 500px">
                        </div>
                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h3>{{$space -> title}}</h3>
                        <span>{{$space -> address}}</span>
                        <p>{{$space -> description}}</p>
                        <div id="summary"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        window.action = "direction"
    </script>
@endpush